public with sharing class WelcomeToPwC {
    public static void printWelcomeMessage() {
        System.debug('Welcome to PwC');
        assert.isNotNull('hello');
    }
    public static void printCopadoMessage() {
        System.debug('Welcome to Copado');
        assert.isNotNull('hello');
}
    public static void printCopadopage1() {
    System.debug('Welcome to Copado-1');
    assert.isNotNull('hello');
}
}